// Expanded, in-page overlay panel: docked to the right edge of the viewport,
// full height, rendered in its own Shadow DOM. Shows LTP/day-change, Market
// Cap, and Analyst Rating, plus a self-hosted lightweight-charts candlestick
// chart for a single company. Only one panel instance exists at a time -- if
// the user hovers a different highlighted company while the panel is open,
// it updates in place (see updateInPlace) instead of stacking a second
// panel.
//
// The chart is rendered entirely with the `lightweight-charts` library
// (Canvas-based, bundled into the extension) fed by candles fetched from the
// background worker. This replaced an earlier TradingView embedded-widget
// approach, which injected a third-party <script>/<iframe> into the host
// page and was silently blocked by some sites' script-src/frame-src CSP.
// Being self-hosted, this chart has no such dependency.

import { createChart, ColorType, type IChartApi, type ISeriesApi, type UTCTimestamp } from 'lightweight-charts';
import css from './ExpandedPanel.css';
import type { GetStockNewsResponse, NewsItem, Quote } from '../../shared/types';
import type { MiniPopupContext } from './MiniPopup';
import { getChartData, getStockNews } from '../../shared/messaging';
import { isInWishlist, toggleWishlist, onWishlistChanged } from '../../shared/wishlistStore';

const NEWS_SHOW_LABEL = 'AI summary of recent updates';
const NEWS_HIDE_LABEL = 'Hide recent updates';

const SVG_NS = 'http://www.w3.org/2000/svg';

/** Four-point sparkle pair — the conventional "generated by AI" mark. */
function buildSparkIcon(): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('class', 'gsh-news-spark');
  svg.setAttribute('aria-hidden', 'true');

  for (const d of [
    'M10 2.5l1.7 4.8 4.8 1.7-4.8 1.7L10 15.5 8.3 10.7 3.5 9l4.8-1.7L10 2.5z',
    'M18 13.5l.9 2.6 2.6.9-2.6.9-.9 2.6-.9-2.6-2.6-.9 2.6-.9.9-2.6z',
  ]) {
    const path = document.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', d);
    path.setAttribute('fill', 'currentColor');
    svg.appendChild(path);
  }
  return svg;
}

/** Box-with-arrow "opens in a new tab" mark. */
function buildExternalIcon(): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('class', 'gsh-panel-tv-icon');
  svg.setAttribute('aria-hidden', 'true');

  for (const d of ['M14 4h6v6', 'M20 4l-8.5 8.5', 'M18 14.5V19a1 1 0 01-1 1H5a1 1 0 01-1-1V7a1 1 0 011-1h4.5']) {
    const path = document.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', d);
    path.setAttribute('fill', 'none');
    path.setAttribute('stroke', 'currentColor');
    path.setAttribute('stroke-width', '2');
    path.setAttribute('stroke-linecap', 'round');
    path.setAttribute('stroke-linejoin', 'round');
    svg.appendChild(path);
  }
  return svg;
}

function buildChevron(): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('class', 'gsh-news-chevron');
  svg.setAttribute('aria-hidden', 'true');

  const path = document.createElementNS(SVG_NS, 'path');
  path.setAttribute('d', 'M6 9l6 6 6-6');
  path.setAttribute('fill', 'none');
  path.setAttribute('stroke', 'currentColor');
  path.setAttribute('stroke-width', '2.2');
  path.setAttribute('stroke-linecap', 'round');
  path.setAttribute('stroke-linejoin', 'round');
  svg.appendChild(path);
  return svg;
}

export class ExpandedPanel {
  private hostEl: HTMLDivElement;
  private shadow: ShadowRoot;
  private tickerEl: HTMLSpanElement;
  private nameEl: HTMLDivElement;
  private ltpEl: HTMLSpanElement;
  private changeEl: HTMLSpanElement;
  private tvLinkEl: HTMLAnchorElement;
  private marketCapEl: HTMLDivElement;
  private volumeEl: HTMLDivElement;
  private kpiRow: HTMLDivElement;
  private starBtn: HTMLButtonElement;
  private widgetContainer: HTMLDivElement;
  private newsContainer: HTMLDivElement;
  private newsToggle: HTMLButtonElement;
  private newsLabel: HTMLSpanElement;
  private newsBody: HTMLDivElement;
  private currentTvSymbol: string | null = null;
  private currentContext: MiniPopupContext | null = null;

  // News is requested as soon as the panel opens so the button can reveal it
  // instantly; the promise is held here until (and if) the user asks for it.
  private newsPromise: Promise<GetStockNewsResponse> | null = null;
  private newsExpanded = false;
  // Same staleness guard as chartRequestId, for company switches mid-flight.
  private newsRequestId = 0;

  private chart: IChartApi | null = null;
  private series: ISeriesApi<'Candlestick'> | null = null;
  private chartEl: HTMLDivElement | null = null;
  private resizeObserver: ResizeObserver | null = null;
  // Incremented on every mountChart() call; a stale async response (from a
  // superseded symbol switch) checks this before touching the DOM/series.
  private chartRequestId = 0;

  constructor(private onClose?: () => void) {
    this.hostEl = document.createElement('div');
    Object.assign(this.hostEl.style, {
      position: 'fixed',
      top: '0',
      right: '0',
      zIndex: '2147483646',
      display: 'none',
    });
    document.documentElement.appendChild(this.hostEl);
    this.shadow = this.hostEl.attachShadow({ mode: 'open' });

    const style = document.createElement('style');
    style.textContent = css;
    this.shadow.appendChild(style);

    const panel = document.createElement('div');
    panel.className = 'gsh-panel';

    const header = document.createElement('div');
    header.className = 'gsh-panel-header';

    const titleRow = document.createElement('div');
    titleRow.className = 'gsh-panel-title-row';

    this.tickerEl = document.createElement('span');
    this.tickerEl.className = 'gsh-panel-ticker';

    const closeBtn = document.createElement('button');
    closeBtn.type = 'button';
    closeBtn.className = 'gsh-panel-close';
    closeBtn.textContent = '\u2715';
    closeBtn.setAttribute('aria-label', 'Close');
    closeBtn.addEventListener('click', () => this.hide());

    this.starBtn = document.createElement('button');
    this.starBtn.type = 'button';
    this.starBtn.className = 'gsh-panel-star';
    this.starBtn.addEventListener('click', () => {
      const context = this.currentContext;
      if (!context) return;
      void toggleWishlist(context).then((starred) => this.paintStar(starred));
    });
    this.paintStar(false);

    const titleActions = document.createElement('div');
    titleActions.className = 'gsh-panel-title-actions';
    titleActions.append(this.starBtn, closeBtn);

    titleRow.append(this.tickerEl, titleActions);

    this.nameEl = document.createElement('div');
    this.nameEl.className = 'gsh-panel-name';

    const priceRow = document.createElement('div');
    priceRow.className = 'gsh-panel-price-row';
    this.ltpEl = document.createElement('span');
    this.ltpEl.className = 'gsh-panel-ltp';
    this.changeEl = document.createElement('span');
    this.changeEl.className = 'gsh-panel-change';

    // Lives in the header rather than under the chart, so unlike the chart
    // container (which mountChart() wipes per symbol) it is built once and
    // only has its href retargeted on each company switch.
    this.tvLinkEl = document.createElement('a');
    this.tvLinkEl.className = 'gsh-panel-tv-link';
    this.tvLinkEl.target = '_blank';
    this.tvLinkEl.rel = 'noopener noreferrer';
    this.tvLinkEl.title = 'View full interactive chart on TradingView';
    this.tvLinkEl.append(document.createTextNode('TradingView'), buildExternalIcon());

    priceRow.append(this.ltpEl, this.changeEl, this.tvLinkEl);

    this.kpiRow = document.createElement('div');
    this.kpiRow.className = 'gsh-panel-kpi-row';
    this.marketCapEl = document.createElement('div');
    this.marketCapEl.className = 'gsh-panel-kpi';
    this.volumeEl = document.createElement('div');
    this.volumeEl.className = 'gsh-panel-kpi';
    this.kpiRow.append(this.marketCapEl, this.volumeEl);

    header.append(titleRow, this.nameEl, priceRow, this.kpiRow);

    this.widgetContainer = document.createElement('div');
    this.widgetContainer.className = 'gsh-panel-widget';

    // Deliberately a sibling of the chart container, which mountChart() wipes
    // wholesale on every symbol change.
    this.newsContainer = document.createElement('div');
    this.newsContainer.className = 'gsh-panel-news';

    this.newsToggle = document.createElement('button');
    this.newsToggle.type = 'button';
    this.newsToggle.className = 'gsh-news-toggle';
    this.newsLabel = document.createElement('span');
    this.newsToggle.append(buildSparkIcon(), this.newsLabel, buildChevron());
    this.newsToggle.addEventListener('click', () => this.toggleNews());

    this.newsBody = document.createElement('div');
    this.newsBody.className = 'gsh-news-body';

    this.newsContainer.append(this.newsToggle, this.newsBody);

    // News sits above the chart: it is the thing being asked for by name, and
    // burying it under a full-height chart made it easy to miss entirely.
    panel.append(header, this.newsContainer, this.widgetContainer);
    this.shadow.appendChild(panel);

    // The panel outlives individual wishlist edits, so the star has to follow
    // changes made elsewhere (the toolbar popup, another tab, another device).
    onWishlistChanged((items) => {
      const symbol = this.currentContext?.yahooSymbol;
      if (!symbol) return;
      this.paintStar(items.some((item) => item.yahooSymbol === symbol));
    });
  }

  show(quote: Quote, context: MiniPopupContext): void {
    // Some publisher pages rebuild large parts of the document and take our
    // host node with them. Re-attaching is cheap and idempotent.
    if (!this.hostEl.isConnected) document.documentElement.appendChild(this.hostEl);

    this.render(quote, context);
    this.hostEl.style.display = 'block';
  }

  updateInPlace(quote: Quote, context: MiniPopupContext): void {
    this.render(quote, context);
  }

  hide(): void {
    this.hostEl.style.display = 'none';
    this.onClose?.();
  }

  isOpen(): boolean {
    return this.hostEl.style.display !== 'none';
  }

  private paintStar(starred: boolean): void {
    this.starBtn.classList.toggle('starred', starred);
    this.starBtn.textContent = starred ? '\u2605' : '\u2606';
    this.starBtn.title = starred ? 'Remove from wishlist' : 'Add to wishlist';
    this.starBtn.setAttribute('aria-label', this.starBtn.title);
    this.starBtn.setAttribute('aria-pressed', String(starred));
  }

  private render(quote: Quote, context: MiniPopupContext): void {
    this.currentContext = context;
    this.tickerEl.textContent = quote.ticker;
    this.nameEl.textContent = context.companyName;
    this.ltpEl.textContent = formatLevel(quote);
    this.tvLinkEl.href = `https://www.tradingview.com/symbols/${context.tvSymbol.replace(':', '-')}/`;

    this.paintStar(false);
    void isInWishlist(context.yahooSymbol).then((starred) => {
      // A stale answer must not restar the panel after a company switch.
      if (this.currentContext?.yahooSymbol === context.yahooSymbol) this.paintStar(starred);
    });

    const direction = quote.change > 0 ? 'positive' : quote.change < 0 ? 'negative' : 'neutral';
    this.changeEl.className = `gsh-panel-change ${direction}`;
    const sign = quote.change > 0 ? '+' : '';
    this.changeEl.textContent = `${sign}${quote.change.toFixed(2)} (${sign}${quote.changePercent.toFixed(2)}%)`;

    // Market cap doesn't exist for an index, so the KPI row is hidden outright
    // rather than showing "N/A" slots.
    const isIndex = quote.kind === 'index';
    this.kpiRow.style.display = isIndex ? 'none' : '';
    if (!isIndex) {
      this.marketCapEl.textContent = quote.marketCap
        ? `Market Cap: ${formatMarketCap(quote.marketCap)}`
        : 'Market Cap: N/A';

      this.volumeEl.textContent = quote.volume
        ? `Volume: ${formatVolume(quote.volume)}${formatVolumeRatio(quote)}`
        : 'Volume: N/A';
    }

    if (this.currentTvSymbol !== context.tvSymbol) {
      this.currentTvSymbol = context.tvSymbol;
      void this.mountChart(context.tvSymbol, context.yahooSymbol);
      this.resetNews(context);
    }
  }

  /**
   * Runs on every company switch: collapses the section and starts the fetch
   * immediately so opening it later is instant. Indices are included because
   * Google News matches on name, and "Nifty IT" is covered as heavily as any
   * single company.
   */
  private resetNews(context: MiniPopupContext): void {
    this.newsRequestId++;
    this.newsExpanded = false;
    this.newsBody.innerHTML = '';
    this.newsBody.style.display = 'none';
    this.newsLabel.textContent = NEWS_SHOW_LABEL;
    this.newsToggle.classList.remove('gsh-news-open');

    this.newsContainer.style.display = '';
    this.newsPromise = getStockNews(context.yahooSymbol, context.ticker, context.companyName);
  }

  private toggleNews(): void {
    if (this.newsExpanded) {
      this.newsExpanded = false;
      this.newsBody.style.display = 'none';
      this.newsLabel.textContent = NEWS_SHOW_LABEL;
      this.newsToggle.classList.remove('gsh-news-open');
      return;
    }

    this.newsExpanded = true;
    this.newsBody.style.display = '';
    this.newsLabel.textContent = NEWS_HIDE_LABEL;
    this.newsToggle.classList.add('gsh-news-open');

    const pending = this.newsPromise;
    if (!pending) return;

    this.newsBody.innerHTML = '';
    this.newsBody.appendChild(buildNewsStatus('Looking for recent updates\u2026'));

    const requestId = this.newsRequestId;
    void pending.then((response) => {
      // Bail if the user switched company or collapsed the section while the
      // request was still in flight.
      if (requestId !== this.newsRequestId || !this.newsExpanded) return;
      this.renderNews(response);
    });
  }

  private renderNews(response: GetStockNewsResponse): void {
    this.newsBody.innerHTML = '';

    if (!response.ok) {
      this.newsBody.appendChild(buildNewsStatus(response.error));
      return;
    }

    if (response.items.length === 0) {
      this.newsBody.appendChild(buildNewsStatus('No news found in the last 48 hours.'));
      return;
    }

    if (!response.summarized) {
      const note = document.createElement('div');
      note.className = 'gsh-news-note';
      note.textContent = 'AI summary unavailable \u2014 showing publisher headlines.';
      this.newsBody.appendChild(note);
    }

    const list = document.createElement('div');
    list.className = 'gsh-news-list';
    for (const item of response.items) {
      list.appendChild(buildNewsItem(item));
    }
    this.newsBody.appendChild(list);
  }

  private teardownChart(): void {
    this.resizeObserver?.disconnect();
    this.resizeObserver = null;
    this.chart?.remove();
    this.chart = null;
    this.series = null;
    this.chartEl = null;
  }

  private async mountChart(tvSymbol: string, yahooSymbol: string): Promise<void> {
    const requestId = ++this.chartRequestId;

    this.teardownChart();
    this.widgetContainer.innerHTML = '';

    const chartEl = document.createElement('div');
    chartEl.className = 'gsh-chart-canvas';
    this.widgetContainer.appendChild(chartEl);
    this.chartEl = chartEl;

    const chart = createChart(chartEl, {
      layout: {
        background: { type: ColorType.Solid, color: '#14161c' },
        textColor: '#c7cad1',
      },
      grid: {
        vertLines: { color: 'rgba(255, 255, 255, 0.06)' },
        horzLines: { color: 'rgba(255, 255, 255, 0.06)' },
      },
      rightPriceScale: { borderColor: 'rgba(255, 255, 255, 0.12)' },
      timeScale: { borderColor: 'rgba(255, 255, 255, 0.12)' },
      crosshair: { mode: 0 },
      width: chartEl.clientWidth,
      height: chartEl.clientHeight,
    });

    const series = chart.addCandlestickSeries({
      upColor: '#00c48c',
      downColor: '#f0554a',
      borderUpColor: '#00c48c',
      borderDownColor: '#f0554a',
      wickUpColor: '#00c48c',
      wickDownColor: '#f0554a',
    });

    this.chart = chart;
    this.series = series;

    const resizeObserver = new ResizeObserver(() => {
      if (!this.chart || !this.chartEl) return;
      this.chart.applyOptions({
        width: this.chartEl.clientWidth,
        height: this.chartEl.clientHeight,
      });
    });
    resizeObserver.observe(chartEl);
    this.resizeObserver = resizeObserver;

    const response = await getChartData(yahooSymbol);

    // The user may have switched to a different company while this request
    // was in flight; a stale response landing here should not touch a chart
    // that's already been torn down / replaced.
    if (requestId !== this.chartRequestId) return;

    if (response.ok && response.candles.length > 0) {
      series.setData(
        response.candles.map((candle) => ({
          time: candle.time as UTCTimestamp,
          open: candle.open,
          high: candle.high,
          low: candle.low,
          close: candle.close,
        }))
      );
      chart.timeScale().fitContent();
    } else {
      this.showChartError();
    }
  }

  private showChartError(): void {
    const msg = document.createElement('div');
    msg.className = 'gsh-chart-error-msg';
    msg.textContent = 'Chart data unavailable right now.';
    this.widgetContainer.appendChild(msg);
  }
}

function buildNewsStatus(text: string): HTMLDivElement {
  const status = document.createElement('div');
  status.className = 'gsh-news-status';
  status.textContent = text;
  return status;
}

// The publisher and a link to the original article are always rendered, never
// summarized away: the summary is a pointer, the source is the record.
function buildNewsItem(item: NewsItem): HTMLDivElement {
  const wrapper = document.createElement('div');
  wrapper.className = 'gsh-news-item';

  const title = document.createElement('a');
  title.className = 'gsh-news-title';
  title.href = item.url;
  title.target = '_blank';
  title.rel = 'noopener noreferrer';
  title.textContent = item.title;
  wrapper.appendChild(title);

  if (item.summary) {
    const summary = document.createElement('p');
    summary.className = 'gsh-news-summary';
    summary.textContent = item.summary;
    wrapper.appendChild(summary);
  }

  const meta = document.createElement('a');
  meta.className = 'gsh-news-meta';
  meta.href = item.url;
  meta.target = '_blank';
  meta.rel = 'noopener noreferrer';
  meta.textContent = item.publishedAt
    ? `${item.source} \u00b7 ${formatAge(item.publishedAt)}`
    : item.source;
  wrapper.appendChild(meta);

  return wrapper;
}

function formatAge(publishedAt: number): string {
  const minutes = Math.round((Date.now() - publishedAt) / 60000);
  if (minutes < 60) return `${Math.max(minutes, 1)}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

function formatCurrency(value: number, currency = 'INR'): string {
  const symbol = currency === 'INR' ? '\u20b9' : '';
  return `${symbol}${value.toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

// An index level is a dimensionless number, not an amount of money, so the
// rupee symbol is dropped for indices.
function formatLevel(quote: Quote): string {
  if (quote.kind === 'index') {
    return quote.ltp.toLocaleString('en-IN', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
  }
  return formatCurrency(quote.ltp, quote.currency);
}

function formatMarketCap(value: number): string {
  const crore = value / 1e7;
  if (crore >= 1e5) return `\u20b9${(crore / 1e5).toFixed(2)} Lakh Cr`;
  return `\u20b9${crore.toFixed(0)} Cr`;
}

/** Share counts, in the crore/lakh units Indian volume is usually quoted in. */
function formatVolume(value: number): string {
  if (value >= 1e7) return `${(value / 1e7).toFixed(2)} Cr`;
  if (value >= 1e5) return `${(value / 1e5).toFixed(2)} L`;
  return value.toLocaleString('en-IN');
}

/**
 * The point of showing volume at all is whether today is unusual, so it is
 * rendered as a multiple of the 3-month average. Yahoo omits the average for
 * thinly covered symbols, in which case the bare figure is shown alone.
 */
function formatVolumeRatio(quote: Quote): string {
  if (!quote.volume || !quote.avgVolume3M) return '';
  return ` (${(quote.volume / quote.avgVolume3M).toFixed(1)}\u00d7 3M avg)`;
}
